export const GET_PERSON_START = "GET_PERSON_START";
export const GET_PERSON_START_ERROR = "GET_PERSON_START_ERROR";
export const GET_PERSON_START_COMPLETE = "GET_PERSON_START_COMPLETE";
export const DEL_PERSON = "DEL_PERSON ";
